services:
  warehouse_db:
    image: postgis/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: warehouse_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db_init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 15

  backend:
    build: ./backend
    container_name: trade_optimizer
    depends_on:
      warehouse_db:
        condition: service_healthy
    environment:
      DB_HOST: warehouse_db
      DB_PORT: 5432
      DB_NAME: warehouse_db
      DB_USER: postgres
      DB_PASS: 1234
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    working_dir: /app
    env_file:
      - .env
    command: >
      sh -c "
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
      "

volumes:
  pgdata:
